language: node_js
node_js:
  - "8"

cache:
  directories:
    - "node_modules"

script: npm test && yarn run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: build
  repo: shinmyung0/shinmyung0.github.io
  committer-from-gh: true
  verbose: true
  target-branch: master